[package]
name = "jupyter-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
crossterm = { version = "0.27.0", features = ["serde", "event-stream"] }
ratatui = { version = "0.27.0", features = ["serde", "macros"] }
